# Generated by Django 4.2.4 on 2023-08-25 07:14

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstats',
            name='ip_address',
            field=models.GenericIPAddressField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='loginstats',
            name='time_zone',
            field=login.models.TimeZoneField(default='UTC', max_length=63),
        ),
    ]
